language: r
cache: packages
latex: false
dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository ppa:opencpu/jq --yes
  - sudo apt-get update  --yes
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libv8-dev
  - sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev 

install:
  - R -e "install.packages('remotes')"
  - R -e "install.packages('tinytex')"
  - R -e "tinytex::install_tinytex()"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh