language: r
cache: packages
latex: false
dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get update  --yes
  - sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev 

install:
  - R -e "install.packages('remotes')"
  
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh